### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by richardasaurus** [onefinestay/django-mediacat#25]
Since mediacat uses the old unsupported Model._meta method it doesn't work with the Django 1.8 Model._meta API

```
  File ".../site-packages/mediacat/fields.py", line 102, in contribute_to_class
    cls._meta.add_virtual_field(self)
AttributeError: 'Options' object has no attribute 'add_virtual_field'
```

There may be other issues, this is just the first thing I noticed.
